# Generated by Django 5.2.6 on 2025-09-25 01:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Author's full name", max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, help_text='Author photo', null=True, upload_to='authors/')),
                ('biography', models.TextField(blank=True, help_text='Author biographical information')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Book title', max_length=255)),
                ('tagline', models.CharField(blank=True, help_text='Brief book description', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Detailed book description')),
                ('image', models.ImageField(blank=True, help_text='Book cover image', null=True, upload_to='books/')),
                ('genre', models.CharField(choices=[('art', 'Art'), ('biography', 'Biography'), ('business', 'Business'), ('chick_lit', 'Chick Lit'), ('childrens', "Children's"), ('christian', 'Christian'), ('classics', 'Classics'), ('comics', 'Comics'), ('contemporary', 'Contemporary'), ('cookbooks', 'Cookbooks'), ('crime', 'Crime'), ('ebooks', 'Ebooks'), ('fantasy', 'Fantasy'), ('fiction', 'Fiction'), ('gay_and_lesbian', 'Gay and Lesbian'), ('graphic_novels', 'Graphic Novels'), ('historical_fiction', 'Historical Fiction'), ('history', 'History'), ('horror', 'Horror'), ('humor_and_comedy', 'Humor and Comedy'), ('manga', 'Manga'), ('memoir', 'Memoir'), ('music', 'Music'), ('mystery', 'Mystery'), ('nonfiction', 'Nonfiction'), ('paranormal', 'Paranormal'), ('philosophy', 'Philosophy'), ('poetry', 'Poetry'), ('psychology', 'Psychology'), ('religion', 'Religion'), ('romance', 'Romance'), ('science', 'Science'), ('science_fiction', 'Science Fiction'), ('self_help', 'Self Help'), ('suspense', 'Suspense'), ('spirituality', 'Spirituality'), ('sports', 'Sports'), ('thriller', 'Thriller'), ('travel', 'Travel'), ('young_adult', 'Young Adult')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.author')),
            ],
            options={
                'ordering': ['title'],
                'unique_together': {('title', 'author')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Star rating from 1-5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('text', models.TextField(blank=True, help_text='Review text content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'book')},
            },
        ),
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_status', models.CharField(choices=[('want_to_read', 'Want to Read'), ('reading', 'Reading'), ('finished', 'Finished'), ('dropped', 'Dropped')], default='want_to_read', max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_started', models.DateTimeField(blank=True, help_text='When user started reading', null=True)),
                ('date_finished', models.DateTimeField(blank=True, help_text='When user finished reading', null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_books', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_added'],
                'unique_together': {('user', 'book')},
            },
        ),
    ]
